//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinFormsAssistant {
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssistantResources_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssistantResources_ES() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinFormsAssistant.AssistantResources_ES", typeof(AssistantResources_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar Búsqueda.
        /// </summary>
        internal static string CancelSearch {
            get {
                return ResourceManager.GetString("CancelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MÓDULO.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE.
        /// </summary>
        internal static string SelectHeader {
            get {
                return ResourceManager.GetString("SelectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para comenzar la escucha tipo walkie-talkie pulse el botón de bajar volumen..
        /// </summary>
        internal static string TutorialText1 {
            get {
                return ResourceManager.GetString("TutorialText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aparecerá el icono del asistente que nos indica que está a la escucha.
        /// </summary>
        internal static string TutorialText2 {
            get {
                return ResourceManager.GetString("TutorialText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A continuación pronuncie las palabras NUEVA {MÓDULO}..
        /// </summary>
        internal static string TutorialText3 {
            get {
                return ResourceManager.GetString("TutorialText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por ejemplo: NUEVA DENUNCIA..
        /// </summary>
        internal static string TutorialText4 {
            get {
                return ResourceManager.GetString("TutorialText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una vez iniciado el módulo podemos pronunciar el nombre de los campos, seguidos del valor para rellenarlos, borrarlos o incluso reiniciar la introducción de los mismos..
        /// </summary>
        internal static string TutorialText5 {
            get {
                return ResourceManager.GetString("TutorialText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por ejemplo: MATRÍCULA 1234ABC PRECEPTO CONDUCCIÓN TEMERARIA..
        /// </summary>
        internal static string TutorialText6 {
            get {
                return ResourceManager.GetString("TutorialText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos campos son de búsqueda, los cuales permiten hacer un filtrado por palabras..
        /// </summary>
        internal static string TutorialText7 {
            get {
                return ResourceManager.GetString("TutorialText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estos campos permiten hacer una selección de una lista de elementos encontrados..
        /// </summary>
        internal static string TutorialText8 {
            get {
                return ResourceManager.GetString("TutorialText8", resourceCulture);
            }
        }
    }
}
